// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: dht.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_null      PacketType = 0
	PacketType_ping      PacketType = 1
	PacketType_store     PacketType = 2
	PacketType_findnode  PacketType = 3
	PacketType_findvalue PacketType = 4
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "null",
		1: "ping",
		2: "store",
		3: "findnode",
		4: "findvalue",
	}
	PacketType_value = map[string]int32{
		"null":      0,
		"ping":      1,
		"store":     2,
		"findnode":  3,
		"findvalue": 4,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_dht_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_dht_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_dht_proto_rawDescGZIP(), []int{0}
}

type State int32

const (
	State_unkonwn State = 0
	State_unfound State = 1
	State_found   State = 2
	State_retry   State = 3
	State_syn     State = 4
	State_ack     State = 5
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "unkonwn",
		1: "unfound",
		2: "found",
		3: "retry",
		4: "syn",
		5: "ack",
	}
	State_value = map[string]int32{
		"unkonwn": 0,
		"unfound": 1,
		"found":   2,
		"retry":   3,
		"syn":     4,
		"ack":     5,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_dht_proto_enumTypes[1].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_dht_proto_enumTypes[1]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_dht_proto_rawDescGZIP(), []int{1}
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=dht.PacketType" json:"type,omitempty"` //消息类型
	Trace []byte     `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`                    //链路跟踪ID
	Pkt   []byte     `protobuf:"bytes,3,opt,name=pkt,proto3" json:"pkt,omitempty"`                        //消息内容
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dht_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_dht_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_dht_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_null
}

func (x *Packet) GetTrace() []byte {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Packet) GetPkt() []byte {
	if x != nil {
		return x.Pkt
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To    uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	St    int64  `protobuf:"varint,3,opt,name=st,proto3" json:"st,omitempty"`                      //send time
	Rt    int64  `protobuf:"varint,4,opt,name=rt,proto3" json:"rt,omitempty"`                      //receive time
	State State  `protobuf:"varint,5,opt,name=state,proto3,enum=dht.State" json:"state,omitempty"` //result state
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dht_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_dht_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_dht_proto_rawDescGZIP(), []int{1}
}

func (x *Ping) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Ping) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Ping) GetSt() int64 {
	if x != nil {
		return x.St
	}
	return 0
}

func (x *Ping) GetRt() int64 {
	if x != nil {
		return x.Rt
	}
	return 0
}

func (x *Ping) GetState() State {
	if x != nil {
		return x.State
	}
	return State_unkonwn
}

type Store struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To    uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	St    int64  `protobuf:"varint,3,opt,name=st,proto3" json:"st,omitempty"`                      //send time
	Rt    int64  `protobuf:"varint,4,opt,name=rt,proto3" json:"rt,omitempty"`                      //receive time
	State State  `protobuf:"varint,5,opt,name=state,proto3,enum=dht.State" json:"state,omitempty"` //result state
	K     uint64 `protobuf:"varint,6,opt,name=k,proto3" json:"k,omitempty"`                        //key
	V     uint64 `protobuf:"varint,7,opt,name=v,proto3" json:"v,omitempty"`                        //value
}

func (x *Store) Reset() {
	*x = Store{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dht_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_dht_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_dht_proto_rawDescGZIP(), []int{2}
}

func (x *Store) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Store) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Store) GetSt() int64 {
	if x != nil {
		return x.St
	}
	return 0
}

func (x *Store) GetRt() int64 {
	if x != nil {
		return x.Rt
	}
	return 0
}

func (x *Store) GetState() State {
	if x != nil {
		return x.State
	}
	return State_unkonwn
}

func (x *Store) GetK() uint64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *Store) GetV() uint64 {
	if x != nil {
		return x.V
	}
	return 0
}

type FindNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  uint64   `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To    uint64   `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	St    int64    `protobuf:"varint,3,opt,name=st,proto3" json:"st,omitempty"`                      //send time
	Rt    int64    `protobuf:"varint,4,opt,name=rt,proto3" json:"rt,omitempty"`                      //receive time
	State State    `protobuf:"varint,5,opt,name=state,proto3,enum=dht.State" json:"state,omitempty"` //result state
	Q     uint64   `protobuf:"varint,6,opt,name=q,proto3" json:"q,omitempty"`                        //query node
	K     []uint64 `protobuf:"varint,7,rep,packed,name=k,proto3" json:"k,omitempty"`                 //k closet
}

func (x *FindNode) Reset() {
	*x = FindNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dht_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNode) ProtoMessage() {}

func (x *FindNode) ProtoReflect() protoreflect.Message {
	mi := &file_dht_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNode.ProtoReflect.Descriptor instead.
func (*FindNode) Descriptor() ([]byte, []int) {
	return file_dht_proto_rawDescGZIP(), []int{3}
}

func (x *FindNode) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *FindNode) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *FindNode) GetSt() int64 {
	if x != nil {
		return x.St
	}
	return 0
}

func (x *FindNode) GetRt() int64 {
	if x != nil {
		return x.Rt
	}
	return 0
}

func (x *FindNode) GetState() State {
	if x != nil {
		return x.State
	}
	return State_unkonwn
}

func (x *FindNode) GetQ() uint64 {
	if x != nil {
		return x.Q
	}
	return 0
}

func (x *FindNode) GetK() []uint64 {
	if x != nil {
		return x.K
	}
	return nil
}

type FindValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To    uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	St    int64  `protobuf:"varint,3,opt,name=st,proto3" json:"st,omitempty"`                      //send time
	Rt    int64  `protobuf:"varint,4,opt,name=rt,proto3" json:"rt,omitempty"`                      //receive time
	State State  `protobuf:"varint,5,opt,name=state,proto3,enum=dht.State" json:"state,omitempty"` //result state
	Q     uint64 `protobuf:"varint,6,opt,name=q,proto3" json:"q,omitempty"`                        //key
	K     uint64 `protobuf:"varint,7,opt,name=k,proto3" json:"k,omitempty"`                        //value
}

func (x *FindValue) Reset() {
	*x = FindValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dht_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValue) ProtoMessage() {}

func (x *FindValue) ProtoReflect() protoreflect.Message {
	mi := &file_dht_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValue.ProtoReflect.Descriptor instead.
func (*FindValue) Descriptor() ([]byte, []int) {
	return file_dht_proto_rawDescGZIP(), []int{4}
}

func (x *FindValue) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *FindValue) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *FindValue) GetSt() int64 {
	if x != nil {
		return x.St
	}
	return 0
}

func (x *FindValue) GetRt() int64 {
	if x != nil {
		return x.Rt
	}
	return 0
}

func (x *FindValue) GetState() State {
	if x != nil {
		return x.State
	}
	return State_unkonwn
}

func (x *FindValue) GetQ() uint64 {
	if x != nil {
		return x.Q
	}
	return 0
}

func (x *FindValue) GetK() uint64 {
	if x != nil {
		return x.K
	}
	return 0
}

var File_dht_proto protoreflect.FileDescriptor

var file_dht_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x68, 0x74,
	0x22, 0x55, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x64, 0x68, 0x74, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6b, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x70, 0x6b, 0x74, 0x22, 0x6c, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x64, 0x68, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x89, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x64, 0x68, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x01, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01,
	0x76, 0x22, 0x8c, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x72, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0a, 0x2e, 0x64, 0x68, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x01, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x07, 0x20, 0x03, 0x28, 0x04, 0x52, 0x01, 0x6b,
	0x22, 0x8d, 0x01, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x72, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0a, 0x2e, 0x64, 0x68, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x01, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x6b,
	0x2a, 0x48, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x10, 0x02, 0x12, 0x0c, 0x0a,
	0x08, 0x66, 0x69, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x66,
	0x69, 0x6e, 0x64, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x10, 0x04, 0x2a, 0x49, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6f, 0x6e, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x75, 0x6e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x65, 0x74, 0x72,
	0x79, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x73, 0x79, 0x6e, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03,
	0x61, 0x63, 0x6b, 0x10, 0x05, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x76, 0x69, 0x6c, 0x6c, 0x61,
	0x67, 0x65, 0x2f, 0x33, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dht_proto_rawDescOnce sync.Once
	file_dht_proto_rawDescData = file_dht_proto_rawDesc
)

func file_dht_proto_rawDescGZIP() []byte {
	file_dht_proto_rawDescOnce.Do(func() {
		file_dht_proto_rawDescData = protoimpl.X.CompressGZIP(file_dht_proto_rawDescData)
	})
	return file_dht_proto_rawDescData
}

var file_dht_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dht_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dht_proto_goTypes = []interface{}{
	(PacketType)(0),   // 0: dht.PacketType
	(State)(0),        // 1: dht.State
	(*Packet)(nil),    // 2: dht.Packet
	(*Ping)(nil),      // 3: dht.Ping
	(*Store)(nil),     // 4: dht.Store
	(*FindNode)(nil),  // 5: dht.FindNode
	(*FindValue)(nil), // 6: dht.FindValue
}
var file_dht_proto_depIdxs = []int32{
	0, // 0: dht.Packet.type:type_name -> dht.PacketType
	1, // 1: dht.Ping.state:type_name -> dht.State
	1, // 2: dht.Store.state:type_name -> dht.State
	1, // 3: dht.FindNode.state:type_name -> dht.State
	1, // 4: dht.FindValue.state:type_name -> dht.State
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dht_proto_init() }
func file_dht_proto_init() {
	if File_dht_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dht_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dht_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dht_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Store); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dht_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dht_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dht_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dht_proto_goTypes,
		DependencyIndexes: file_dht_proto_depIdxs,
		EnumInfos:         file_dht_proto_enumTypes,
		MessageInfos:      file_dht_proto_msgTypes,
	}.Build()
	File_dht_proto = out.File
	file_dht_proto_rawDesc = nil
	file_dht_proto_goTypes = nil
	file_dht_proto_depIdxs = nil
}
